### ISSUE TITLE
Problem with HTTPS proxy

### ISSUE THREAD

**Issue by nstufano** [orrc/google-play-android-publisher-plugin#6]
Hi,
in Jenkins there is only HTTP Proxy, but this publisher plugin needs HTTPS Proxy.

Can you add a specific option to set HTTPS proxy in your plugin? 
I try to set -Dhttps.proxyHost and -Dhttps.proxyPort in Java_Args of Jenkins (/etc/sysconfig/jenkins). Your plugin is fully functional with this workaround but I cannot build my java project because Jenkins don't find SCM server.

Can you help me? 

Thanks

**Comment by orrc** [comment]
Using the proxy options is the correct way to go, as documented on the plugin's wiki page:
https://plugins.jenkins.io/google-play-android-publisher#GooglePlayAndroidPublisherPlugin-java.net.SocketTimeoutException:connecttimedout

You should ask your network administrator about the correct settings; perhaps you need to exclude your SCM server via the `nonProxyHosts` options in Java.
